name=ESP32P4-CameraWeb
version=0.1.0
author=Prince223889
maintainer=Prince223889
sentence=Lightweight web UI for ESP32-P4 MIPI-CSI cameras
paragraph=Lightweight web UI for ESP32-P4 MIPI-CSI cameras Built for Arduino-ESP32 and designed for reusable embedded projects.
category=Communication
url=https://github.com/Prince223889/ESP32P4-CameraWeb
architectures=esp32
