name: compile
on: [push, pull_request, workflow_dispatch]
jobs:
  arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Prince223889/ESP32P4-Camera
          path: /tmp/ESP32P4-Camera
      - uses: arduino/setup-arduino-cli@v2
      - run: arduino-cli core update-index
      - run: arduino-cli core install esp32:esp32@3.3.11
      - run: mkdir -p "$HOME/Arduino/libraries" && cp -r /tmp/ESP32P4-Camera "$HOME/Arduino/libraries/ESP32P4-Camera"
      - run: arduino-cli compile --fqbn 'esp32:esp32:esp32p4:PSRAM=enabled,USBMode=default,ChipVariant=postv3,FlashSize=16M,PartitionScheme=app3M_fat9M_16MB' --libraries "$HOME/Arduino/libraries" examples/WebCamera/WebCamera.ino
